### PR TITLE
Upgrade fmt to 8.0.0 (from 7.1.3) after folly upgrade to 2022.03.14.00

### LINKED ISSUE #1337: Fail to build on Ubuntu after folly v2022.03.14.00 upgrade
`../folly/IPAddressV4.cpp:73:64:   required from here
../folly/Range.h:1558:68: error: passing ‘const fmt::v7::formatter<folly::Range<const char*> >’ as ‘this’ argument discards qualifiers [-fpermissive]
 1558 |     return formatter<string_view>::format({s.data(), s.size()}, ctx);
      |                                                                    ^
In file incl`

 fmtlib/fmt upgrade to 8.0.0 is also needed setup-ubuntu.sh.

### PR DESCRIPTION
**Pull request by dingqiaoyi**
fix #1337

### CODE REVIEW

**Comment by mbasmanova** [comment]
CC: @kgpai

**Review by mbasmanova — APPROVED** [review]
@dingqiaoyi Thanks.
