### PR TITLE
fix(cuDF): Fix issue caused by merging two cudf PRs together

### LINKED ISSUE #14899: CI is broken due to cuDF
### Problem description

```
In file included from /__w/velox/velox/velox/experimental/cudf/tests/OrderByTest.cpp:17:
/__w/velox/velox/./velox/experimental/cudf/exec/ToCudf.h: In constructor 'facebook::velox::cudf_velox::CudfOptions::CudfOptions(bool)':
/__w/velox/velox/./velox/experimental/cudf/exec/ToCudf.h:77:9: error: class 'facebook::velox::cudf_velox::CudfOptions' does not have any field named 'cudfTableScan'
   77 |         cudfTableScan(FLAGS_velox_cudf_table_scan),
      |         ^~~~~~~~~~~~~
/__w/velox/velox/./velox/experimental/cudf/exec/ToCudf.h:77:23: error: 'FLAGS_velox_cudf_table_scan' was not declared in this scope; did you mean 'FLAGS_velox_cudf_enabled'?
   77 |         cudfTableScan(FLAGS_velox_cudf_table_scan),
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                       FLAGS_velox_cudf_enabled
```

Introduced by https://github.com/facebookincubator/velox/pull/14294

PR did not have the CI tests running fix https://github.com/facebookincubator/velox/pull/14870

### System information

CI https://github.com/facebookincubator/velox/actions/runs/17835856648/job/50712755769

### CMake log

```bash

```

### PR DESCRIPTION
**Pull request by devavret**
PR #14441 and #14294 went in at the same time and had a merge conflict, resulting in cuDF build to be broken and CI to fail. This PR rectifies that.
Closes #14899

### CODE REVIEW

**Review by shrshi — APPROVED** [review]
Thanks for the fix!

**Review by mhaseeb123 — APPROVED** [review]

**Review by majetideepak — APPROVED** [review]
