### ISSUE TITLE
CI is broken due to cuDF

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#14899]
### Problem description

```
In file included from /__w/velox/velox/velox/experimental/cudf/tests/OrderByTest.cpp:17:
/__w/velox/velox/./velox/experimental/cudf/exec/ToCudf.h: In constructor 'facebook::velox::cudf_velox::CudfOptions::CudfOptions(bool)':
/__w/velox/velox/./velox/experimental/cudf/exec/ToCudf.h:77:9: error: class 'facebook::velox::cudf_velox::CudfOptions' does not have any field named 'cudfTableScan'
   77 |         cudfTableScan(FLAGS_velox_cudf_table_scan),
      |         ^~~~~~~~~~~~~
/__w/velox/velox/./velox/experimental/cudf/exec/ToCudf.h:77:23: error: 'FLAGS_velox_cudf_table_scan' was not declared in this scope; did you mean 'FLAGS_velox_cudf_enabled'?
   77 |         cudfTableScan(FLAGS_velox_cudf_table_scan),
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                       FLAGS_velox_cudf_enabled
```

Introduced by https://github.com/facebookincubator/velox/pull/14294

PR did not have the CI tests running fix https://github.com/facebookincubator/velox/pull/14870

### System information

CI https://github.com/facebookincubator/velox/actions/runs/17835856648/job/50712755769

### CMake log

```bash

```

**Comment by majetideepak** [comment]
CC: @karthikeyann @devavret

**Comment by devavret** [comment]
On it! ~I don't know how this escaped.~ This probably happened because of two PRs merging at the same time. #14294 and #14441
