### ISSUE TITLE
Build failing with undefined reference to `facebook::velox::functions::registerArraySplitIntoChunksFunctions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

### ISSUE THREAD

**Issue by Yuhta** [facebookincubator/velox#16785]
### Problem description
https://github.com/facebookincubator/velox/actions/runs/23137141524/job/67203739922
https://github.com/facebookincubator/velox/actions/runs/23140412256/job/67214929617

### System information

N/A

### CMake log

```
DEBUG FAILED: velox/common/file/tests/velox_file_test 
DEBUG : && /opt/rh/gcc-toolset-12/root/bin/g++ -mavx2 -mfma -mavx -mf16c -mlzcnt -mbmi2 -D USE_VELOX_COMMON_BASE -D HAS_UNCAUGHT_EXCEPTIONS -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wno-implicit-fallthrough          -Wno-class-memaccess          -Wno-comment          -Wno-int-in-bool-context          -Wno-redundant-move          -Wno-array-bounds          -Wno-maybe-uninitialized          -Wno-unused-result          -Wno-format-overflow          -Wno-strict-aliasing -Wno-restrict -Werror -g -Wl,-export-dynamic velox/common/file/tests/CMakeFiles/velox_file_test.dir/FileTest.cpp.o velox/common/file/tests/CMakeFiles/velox_file_test.dir/FileInputStreamTest.cpp.o velox/common/file/tests/CMakeFiles/velox_file_test.dir/FileIoTracerTest.cpp.o velox/common/file/tests/CMakeFiles/velox_file_test.dir/FileUtilsTest.cpp.o -o velox/common/file/tests/velox_file_test  -Wl,-rpath,/__w/velox/velox/velox_main/_build/debug/lib:/usr/local/lib64:/usr/local/lib  velox/common/file/tests/libvelox_file_test_utils.a  lib/libvelox.so  /usr/lib64/libgmock.so.1.11.0  /usr/lib64/libgtest_main.so.1.11.0  /usr/local/lib64/libgflags.so.2.2.2  /usr/local/lib64/libglog.so  /usr/lib64/liblz4.so  /usr/lib64/libre2.so.9.0.0  /usr/local/lib64/libgeos.so.3.10.7  /usr/lib64/libdouble-conversion.so.3.1.5  /usr/local/lib64/libsnappy.a  /usr/local/lib64/libprotobuf.a  /usr/lib64/libzstd.so  /usr/lib64/libz.so  /usr/local/lib64/libarrow.a  /usr/local/lib/libthrift.a  velox/tpch/gen/dbgen/libdbgen.a  /usr/local/lib/libfolly.so.0.58.0-dev  /usr/local/lib/libboost_context.so.1.84.0  /usr/local/lib/libboost_filesystem.so.1.84.0  /usr/local/lib/libboost_program_options.so.1.84.0  /usr/local/lib/libboost_regex.so.1.84.0  /usr/local/lib/libboost_thread.so.1.84.0  /usr/local/lib/libboost_atomic.so.1.84.0  /usr/lib64/libdouble-conversion.so  /usr/local/lib64/libgflags.so.2.2.2  /usr/local/lib64/libglog.so  /usr/lib64/libevent.so  /usr/lib64/libz.so  /usr/lib64/libssl.so  /usr/lib64/libcrypto.so  /usr/lib64/liblz4.so  /usr/lib64/libzstd.so  /usr/local/lib64/libsnappy.a  /usr/lib64/libdwarf.so  /usr/lib64/libsodium.so  /usr/local/lib64/libfmt.a  /usr/local/lib64/libsimdjson.a  /usr/local/lib/libstemmer.a  /usr/local/lib/libduckdb_static.a  -ldl  /usr/local/lib/libduckdb_fsst.a  /usr/local/lib/libduckdb_fmt.a  /usr/local/lib/libduckdb_pg_query.a  /usr/local/lib/libduckdb_re2.a  /usr/local/lib/libduckdb_miniz.a  /usr/local/lib/libduckdb_utf8proc.a  /usr/local/lib/libduckdb_hyperloglog.a  /usr/local/lib/libduckdb_fastpforlib.a  /usr/local/lib/libduckdb_mbedtls.a  /usr/local/lib/libjemalloc_extension.a  /usr/lib64/libgtest.so.1.11.0 && :
DEBUG /opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: lib/libvelox.so: undefined reference to `facebook::velox::functions::registerArraySplitIntoChunksFunctions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
DEBUG collect2: error: ld returned 1 exit status
```

**Comment by Yuhta** [comment]
These are caused by #16584, @allenshen13 can you take a look?

**Comment by kgpai** [comment]
Going to revert this change to keep builds green.

Please fix with the change in another PR.

**Comment by czentgr** [comment]
The merge commit https://github.com/facebookincubator/velox/commit/a3770113e2aca39f11824bbe62ec4421217aabd6 for https://github.com/facebookincubator/velox/pull/16584 was missing the file addition to the CMakeLists.txt which is the fix from https://github.com/facebookincubator/velox/pull/16781.

So something happened with the import/merge of the PR that missed this change.
