### ISSUE TITLE
Build failure on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by damianr99** [facebookincubator/velox#308]
```
[8/612] Building CXX object velox/aggregates/CMakeFi...velox_aggregates.dir/ApproxPercentileAggregate.cpp.
FAILED: velox/aggregates/CMakeFiles/velox_aggregates.dir/ApproxPercentileAggregate.cpp.o 
/usr/bin/c++  -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_CONTEXT_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DFMT_LOCALE -DGFLAGS_IS_A_DLL=0 -I../../. -isystem ../../velox -isystem ../../velox/external -isystem ../../velox/external/duckdb -isystem ../../deps/include -mavx2 -mfma -mavx -mf16c  -mbmi2 -march=native -D USE_VELOX_COMMON_BASE -g -D HAS_UNCAUGHT_EXCEPTIONS -Werror -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wno-implicit-fallthrough          -Wno-empty-body          -Wno-class-memaccess          -Wno-comment          -Wno-int-in-bool-context          -Wno-redundant-move          -Wno-type-limits -O3 -DNDEBUG   -std=gnu++17 -MD -MT velox/aggregates/CMakeFiles/velox_aggregates.dir/ApproxPercentileAggregate.cpp.o -MF velox/aggregates/CMakeFiles/velox_aggregates.dir/ApproxPercentileAggregate.cpp.o.d -o velox/aggregates/CMakeFiles/velox_aggregates.dir/ApproxPercentileAggregate.cpp.o -c ../../velox/aggregates/ApproxPercentileAggregate.cpp
In file included from ../.././velox/vector/BaseVector.h:38,
                 from ../.././velox/vector/ComplexVector.h:26,
                 from ../.././velox/connectors/Connector.h:20,
                 from ../.././velox/core/PlanNode.h:18,
                 from ../.././velox/exec/Aggregate.h:19,
                 from ../../velox/aggregates/ApproxPercentileAggregate.cpp:19:
../.././velox/vector/VectorStream.h: In instantiation of ??T facebook::velox::ByteStream::read() [with T = double]??:
../../velox/aggregates/ApproxPercentileAggregate.cpp:52:8:   required from ??folly::TDigest facebook::velox::aggregate::{anonymous}::deserialize(TByteStream&) [with TByteStream = facebook::velox::ByteStream]??
../../velox/aggregates/ApproxPercentileAggregate.cpp:99:32:   required from here
../.././velox/vector/VectorStream.h:297:41: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  297 |     return *reinterpret_cast<const T*>(&value);
      |                                         ^~~~~
cc1plus: all warnings being treated as errors
[15/612] Building CXX object velox/aggregates/CMakeFiles/velox_aggregates.dir/MinMaxByAggregates.cpp.o
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:50: build] Error 1
make[1]: Leaving directory '/space2/damianr/tmp/velox'
make: *** [Makefile:57: release] Error 2
~/t/s/velox> :main! [status=2] cat /etc/issue
Ubuntu 20.04.2 LTS \n \l

~/t/s/velox> :main! /usr/bin/c++ --version
c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by pedroerp** [comment]
I've seen this before. Does this happen in both debug and release compilation modes?

**Comment by damianr99** [comment]
It works on debug mode, fails on release.  (debug mode compiles, but many of the test programs fail to link due to a missing `-lpthread`, forcing adding the `-lpthread` option got `make debug` working successfully).

**Comment by pedroerp** [comment]
@damianr99 @wenleix this is should fix the second half of the issue: 

> https://github.com/facebookincubator/velox/pull/372

This PR disable strict aliasing (and other warnings) to ensure we can compile in Ubuntu 20.04.

**Comment by damianr99** [comment]
This now builds successfully for me, thanks!

**Comment by pedroerp** [comment]
Great, closing the issue!
