### PR TITLE
Fix CacheInputTest and FusedLoad

### PR DESCRIPTION
**Pull request by oerling**
- Add synchronization to threaded CacheTest.
- Fix initialization order of FusedLoad.
- Add IoStatistics members for tracking cache usage.
- Fix destruction order of caches and FileIds. FileIds must be live
  on destruction of caches that hold StringIdLeases.

### CODE REVIEW

**Comment by mbasmanova** [comment]
@oerling There are build failures:

```
FAILED: velox/common/caching/tests/CMakeFiles/velox_cache_test.dir/AsyncDataCacheTest.cpp.o 
ccache /opt/rh/gcc-toolset-9/root/bin/g++  -DBOOST_ALL_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DFMT_LOCALE -DFMT_SHARED -DGFLAGS_IS_A_DLL=0 -I../../. -isystem ../../velox -isystem ../../velox/external -isystem ../../velox/external/duckdb -mavx2 -mfma -mavx -mf16c  -mbmi2 -march=native -D USE_VELOX_COMMON_BASE -g -D HAS_UNCAUGHT_EXCEPTIONS -Werror -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wno-implicit-fallthrough          -Wno-empty-body          -Wno-class-memaccess          -Wno-comment          -Wno-int-in-bool-context          -Wno-redundant-move          -Wno-type-limits -g   -std=gnu++17 -MD -MT velox/common/caching/tests/CMakeFiles/velox_cache_test.dir/AsyncDataCacheTest.cpp.o -MF velox/common/caching/tests/CMakeFiles/velox_cache_test.dir/AsyncDataCacheTest.cpp.o.d -o velox/common/caching/tests/CMakeFiles/velox_cache_test.dir/AsyncDataCacheTest.cpp.o -c ../../velox/common/caching/tests/AsyncDataCacheTest.cpp
../../velox/common/caching/tests/AsyncDataCacheTest.cpp: In member function 'void AsyncDataCacheTest::initializeCache(int64_t)':
../../velox/common/caching/tests/AsyncDataCacheTest.cpp:34:23: error: 'createDefaultInstance' is not a member of 'facebook::velox::memory::MappedMemory'
   34 |         MappedMemory::createDefaultInstance(), maxBytes);
      |                       ^~~~~~~~~~~~~~~~~~~~~
```

File: .circleci/config.yml [hunk 1]
```diff
@@ -110,15 +110,10 @@ jobs:
           paths:
             - .ccache/
       - run:
-          name: "Run Unit Tests"
+          name: Run Unit Tests
           command: |
             make unittest NUM_THREADS=16
           no_output_timeout: 1h
-      - run:
```
Comment (mbasmanova) [inline .circleci/config.yml:117]: Bad merge?

File: velox/type/Filter.h [hunk 2]
```diff
@@ -235,7 +235,7 @@ class Filter {
   const FilterKind kind_;
 };
 
-/// TODO Check if this filter is needed. This should not be passed down.
+// TODO Check if this filter is needed. The should not be passed down.
```
Comment (mbasmanova) [inline velox/type/Filter.h:238]: Bad merge?

**Review by mbasmanova — CHANGES_REQUESTED** [review]
@oerling There are a lot of unrelated / unintended changes which suggest something like a bad merge happened. Please, double check.

File: velox/common/caching/AsyncDataCache.h [hunk 3]
```diff
@@ -332,7 +345,7 @@ enum class LoadState { kPlanned, kLoading, kCancelled, kLoaded };
 // thread gets there first, then the query thread will do the
 // IO. The IO is also cancelled as a unit. FusedLoad holds a pin on
 // all the entries it concerns. The pins are released after the IO
-// completes or is cancelled. An entry that references a FusedLoad
+// completes or is cpriancelled. An entry that references a FusedLoad
```
Comment (mbasmanova) [inline velox/common/caching/AsyncDataCache.h:348]: typo: cpriancelled

File: velox/common/caching/tests/AsyncDataCacheTest.cpp [hunk 4]
```diff
@@ -30,8 +30,8 @@ class AsyncDataCacheTest : public testing::Test {
  protected:
   static constexpr int32_t kNumFiles = 100;
   void initializeCache(int64_t maxBytes) {
-    cache_ =
-        std::make_shared<AsyncDataCache>(MappedMemory::getInstance(), maxBytes);
+    cache_ = std::make_shared<AsyncDataCache>(
+        MappedMemory::createDefaultInstance(), maxBytes);
```
Comment (mbasmanova) [inline velox/common/caching/tests/AsyncDataCacheTest.cpp:34]: MappedMemory::createDefaultInstance() - it would be nice to stop using the default instance

**Review by mbasmanova — APPROVED** [review]
