### ISSUE TITLE
Fail to build on Ubuntu after folly v2022.03.14.00 upgrade

### ISSUE THREAD

**Issue by dingqiaoyi** [facebookincubator/velox#1337]
`../folly/IPAddressV4.cpp:73:64:   required from here
../folly/Range.h:1558:68: error: passing ‘const fmt::v7::formatter<folly::Range<const char*> >’ as ‘this’ argument discards qualifiers [-fpermissive]
 1558 |     return formatter<string_view>::format({s.data(), s.size()}, ctx);
      |                                                                    ^
In file incl`

 fmtlib/fmt upgrade to 8.0.0 is also needed setup-ubuntu.sh.
