### ISSUE TITLE
Mac build is failing: SimdUtil.h:404:11: error: indirection requires pointer operand ('int' invalid)

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#7765]
### Problem description

https://app.circleci.com/pipelines/github/facebookincubator/velox/39444/workflows/32e63716-fedb-494b-abf2-9afa855d446d/jobs/267750

The build started failing after #7726

CC: @oerling @Yuhta @pedroerp @kgpai 

### System information

CI

### CMake log

```bash
In file included from /Users/distiller/project/velox/common/base/tests/SimdUtilTest.cpp:17:
/Users/distiller/project/./velox/common/base/SimdUtil.h:404:11: error: indirection requires pointer operand ('int' invalid)
          *reinterpret_cast<const T*>(&data)[i];
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/distiller/project/./velox/common/base/SimdUtil.h:434:5: note: in instantiation of function template specialization 'facebook::velox::simd::storeLeading<int, xsimd::neon64>' requested here
    storeLeading<TData, A>(values, mask, numLeft, output + i);
    ^
/Users/distiller/project/velox/common/base/tests/SimdUtilTest.cpp:243:11: note: in instantiation of function template specialization 'facebook::velox::simd::transpose<int, int, xsimd::neon64>' requested here
    simd::transpose(
          ^
In file included from /Users/distiller/project/velox/common/base/tests/SimdUtilTest.cpp:17:
/Users/distiller/project/./velox/common/base/SimdUtil.h:404:11: error: indirection requires pointer operand ('long long' invalid)
          *reinterpret_cast<const T*>(&data)[i];
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/distiller/project/./velox/common/base/SimdUtil.h:434:5: note: in instantiation of function template specialization 'facebook::velox::simd::storeLeading<long long, xsimd::neon64>' requested here
    storeLeading<TData, A>(values, mask, numLeft, output + i);
    ^
/Users/distiller/project/velox/common/base/tests/SimdUtilTest.cpp:254:11: note: in instantiation of function template specialization 'facebook::velox::simd::transpose<long long, int, xsimd::neon64>' requested here
    simd::transpose(
          ^
2 errors generated.
```

**Comment by duanmeng** [comment]
@mbasmanova This should be caused by trying to dereference a non-pointer type.
