### ISSUE TITLE
[cuDF] Add a step to the adapters build to verify that Velox links to cuDF

### ISSUE THREAD

**Issue by GregoryKimball** [facebookincubator/velox#14867]
### Description

**Is your feature request related to a problem? Please describe.**
As of Sep 2025, Velox's CI workers do not include GPUs, and this means that we can build Velox-cuDF in CI but we cannot yet test it. 

#14866 fixed an issue introduced in #13818 that unintentionally disabled building Velox-cuDF in the adapters build. As a result we missed a compilation error (addressed in #14799) that should have been caught as a CI failure in the adapters build.

**Describe the solution you'd like**
We should add a step in the adapters build, after [Make Release Build](https://github.com/facebookincubator/velox/blob/de31a3eb07b5ec3cbd1e6320a989fcb2ee1a95a7/.github/workflows/linux-build-base.yml#L85), to verify that cuDF has been built and that Velox correctly links to it.

**Additional context**
NVIDIA has GPU CI for Velox-cuDF under development at https://github.com/rapidsai/velox-testing. As of Sep 2025, this repo is private and we are working to release it as open-source software.
