### ISSUE TITLE
error: binding reference of type ‘MemoryPool*&’ to ‘MemoryPool* const’ discards qualifiers

### ISSUE THREAD

**Issue by jackylee-ch** [facebookincubator/velox#4067]
### Problem description

This problem occurs when trying to compile with gcc12.1. This is a bug([Wrong overload selected in base class](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105637)) of gcc12.1, , and it has been fixed in 12.2.
```
velox/vector/FlatVector-inl.h:111:19: error: binding reference of type ‘facebook::velox::memory::MemoryPool*&’ to ‘facebook::velox::memory::MemoryPool* const’ discards qualifiers
111 |       BaseVector::pool_,                                                                    
    |       ~~~~~~~~~~~~^~~~~  
velox/vector/DictionaryVector-inl.h:165:19: error: binding reference of type ‘facebook::velox::memory::MemoryPool*&’ to ‘facebook::velox::memory::MemoryPool* const’ discards qualifiers
165 |       BaseVector::pool_,                                                                    
    |       ~~~~~~~~~~~~^~~~~  
```

Users who encounter this problem need to upgrade gcc12.1 to 12.2 or make the following changes to the code.
```
Change `BaseVector::pool_` to `FlatVector::pool_` in velox/vector/FlatVector-inl.h:111.
Change `BaseVector::pool_` to `DictionaryVector::pool_` in velox/vector/DictionaryVector-inl.h:165.
```

### System information

Velox System Info v0.0.2
Commit: ece80e07c571eb7bf67d7965c8a30f674425ec7b
CMake Version: 3.25.2
System: Linux-5.10.0-1.0.0.21
Arch: x86_64
C++ Compiler: /usr/bin/g++
C++ Compiler Version: 12.1.0
C Compiler: /usr/bin/gcc
C Compiler Version: 12.1.0
CMake Prefix Path: /usr/local;/usr;/;/opt/local/cmake-3.25.2-linux-x86_64;/usr/local;/usr/X11R6;/usr/pkg

**Comment by assignUser** [comment]
Thank you for your report and solution! 

As this is a bug in gcc 12.1 I am going to close this as completed as I don't think it makes sense to introduce edge-case handling for a very recent minor release that was superseded within 6 month.

But should anyone come across this error you report will make it easy to fix so thank you!
