### PR TITLE
Fix build error

### LINKED ISSUE #7765: Mac build is failing: SimdUtil.h:404:11: error: indirection requires pointer operand ('int' invalid)
### Problem description

https://app.circleci.com/pipelines/github/facebookincubator/velox/39444/workflows/32e63716-fedb-494b-abf2-9afa855d446d/jobs/267750

The build started failing after #7726

CC: @oerling @Yuhta @pedroerp @kgpai 

### System information

CI

### CMake log

```bash
In file included from /Users/distiller/project/velox/common/base/tests/SimdUtilTest.cpp:17:
/Users/distiller/project/./velox/common/base/SimdUtil.h:404:11: error: indirection requires pointer operand ('int' invalid)
          *reinterpret_cast<const T*>(&data)[i];
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/distiller/project/./velox/common/base/SimdUtil.h:434:5: note: in instantiation of function template specialization 'facebook::velox::simd::storeLeading<int, xsimd::neon64>' requested here
    storeLeading<TData, A>(values, mask, numLeft, output + i);
    ^
/Users/distiller/project/velox/common/base/tests/SimdUtilTest.cpp:243:11: note: in instantiation of function template specialization 'facebook::velox::simd::transpose<int, int, xsimd::neon64>' requested here
    simd::transpose(
          ^
In file included from /Users/distiller/project/velox/common/base/tests/SimdUtilTest.cpp:17:
/Users/distiller/project/./velox/common/base/SimdUtil.h:404:11: error: indirection requires pointer operand ('long long' invalid)
          *reinterpret_cast<const T*>(&data)[i];
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/distiller/project/./velox/common/base/SimdUtil.h:434:5: note: in instantiation of function template specialization 'facebook::velox::simd::storeLeading<long long, xsimd::neon64>' requested here
    storeLeading<TData, A>(values, mask, numLeft, output + i);
    ^
/Users/distiller/project/velox/common/base/tests/SimdUtilTest.cpp:254:11: note: in instantiation of function template specialization 'facebook::velox::simd::transpose<long long, int, xsimd::neon64>' requested here
    simd::transpose(
          ^
2 errors generated.
```

### PR DESCRIPTION
**Pull request by duanmeng**
A build error is caused by trying to dereference a non-pointer type.
```C++
reinterpret_cast<T*>(destination)[i] =
          *reinterpret_cast<const T*>(&data)[i];
```

Fixes #7765

### CODE REVIEW

**Review by majetideepak — APPROVED** [review]

**Review by mbasmanova — COMMENTED** [review]
@Yuhta Jimmy, would you help review this PR?

**Comment by Yuhta** [comment]
We probably should have a SSE4.2 build (non-AVX) at diff time to guard against these bugs

**Comment by majetideepak** [comment]
> We probably should have a SSE4.2 build (non-AVX) at diff time to guard against these bugs

Surprisingly, the macOS build did not fail in the https://github.com/facebookincubator/velox/pull/7726. But it started to fail after the https://github.com/facebookincubator/velox/pull/7726 landed on the main branch.

**Comment by duanmeng** [comment]
> > We probably should have a SSE4.2 build (non-AVX) at diff time to guard against these bugs
> 
> Surprisingly, the macOS build did not fail in #7726. But it started to fail after #7726 landed on the main branch.

@majetideepak The macOS build in CI is using macOS with intel CPU that defined AVX2, and in `SimdUtil::storeLeading` the two branches `if constexpr` or `else if constexpr` is guaranteed to be true, so the codes in the `else` block are ignored by the compiler?
