### PR TITLE
fix: Fix build error caused by bad merge

### PR DESCRIPTION
**Pull request by jagill**
Summary:
In #13771 we merged a change to how we deserialize envelopes.
But between accepting and shipping another use of the old pattern was
committed.  This fixes that usage.

Differential Revision: D78488999

### CODE REVIEW

**Review by mbasmanova — APPROVED** [review]

**Comment by yuandagits** [comment]
Build still seems broken?

```
/Users/runner/work/velox/velox/./velox/functions/prestosql/GeometryFunctions.h:826:52: error: no member named 'deserializeEnvelope' in 'facebook::velox::functions::geospatial::GeometryDeserializer'
  826 |         result = geospatial::GeometryDeserializer::deserializeEnvelope(geometry)
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/runner/work/velox/velox/./velox/functions/prestosql/geospatial/GeometryUtils.h:34:5: note: expanded from macro 'GEOS_TRY'
   34 |     func                                                         \
      |     ^~~~
      ```
