### PR TITLE
fix: Fix ~UnknownType() used before its definition

### PR DESCRIPTION
**Pull request by zhztheplayer**
Addressing the following build error:

```
[ 56%] Building CXX object _deps/velox-build/velox/buffer/CMakeFiles/velox.dir/__/common/caching/SsdCache.cpp.o
In file included from /velox4j/src/main/cpp/build/_deps/velox-src/./velox/common/memory/ByteStream.h:20,
                 from /velox4j/src/main/cpp/build/_deps/velox-src/./velox/common/memory/HashStringAllocator.h:20,
                 from /velox4j/src/main/cpp/build/_deps/velox-src/./velox/common/base/BigintIdMap.h:22,
                 from /velox4j/src/main/cpp/build/_deps/velox-src/velox/common/base/BigintIdMap.cpp:17:
/velox4j/src/main/cpp/build/_deps/velox-src/./velox/type/Type.h: In static member function 'static std::shared_ptr<const facebook::velox::UnknownType> facebook::velox::TypeFactory<facebook::velox::TypeKind::UNKNOWN>::create()':
/velox4j/src/main/cpp/build/_deps/velox-src/./velox/type/Type.h:1489:34: error: 'virtual constexpr facebook::velox::UnknownType::~UnknownType()' used before its definition
 1489 |     static constexpr UnknownType kInstance;
      |                                  ^~~~~~~~~
gmake[3]: *** [_deps/velox-build/velox/buffer/CMakeFiles/velox.dir/__/common/base/BigintIdMap.cpp.o] Error 1
```

Fixes https://github.com/facebookincubator/velox/issues/14309

Caused by https://github.com/facebookincubator/velox/pull/14177

### CODE REVIEW

**Comment by zhztheplayer** [comment]
cc @rui-mo @kKPulla

**Review by mbasmanova — APPROVED** [review]
Thanks.

**Comment by mbasmanova** [comment]
CC: @MBkkt

**Comment by MBkkt** [comment]
@zhztheplayer Hi, I think it's ok to change, although produced code will be a little worse (now it's magic static aka spinlock for first access), but it's still better than it was before.
I think dtor of unknown type is trivial and defined before usage. Probably this error related to different compiler/compilation settings.

And it's strange that the almost same usage for ScalarType works as expected.
Maybe you're using some flag, forgot how it's named to deduplicate definition of virtual function that defined in headers?

Anyway I think it can be changed in future back to constexpr, when supported compilers will be updated

**Comment by zhztheplayer** [comment]
@MBkkt Thanks for the detailed followup.

> And it's strange that the almost same usage for ScalarType works as expected. Maybe you're using some flag, forgot how it's named to deduplicate definition of virtual function that defined in headers?

Yes, I'll have a look. The issue looked general at first glance as it failed an internal CI, the Velox4J CI, my local build, etc.

I assume ScalarType is a template class which makes some subtle difference between its compilation and the UnknownType.

**Comment by zhztheplayer** [comment]
I saw you [mentioned](https://github.com/facebookincubator/velox/issues/14309#issuecomment-3144733849) the error may be related to C++ standard version, though I was on C++ 20 already:

```
-- [cpr] Building cpr from source
-- [cpr] CXX standard of parent project: 20
-- [cpr] CXX standard: 20
-- [cpr] C++ Requests CMake Options
-- [cpr] =======================================================
...
```

My env:

```
Velox System Info v0.0.2
Commit: 168427e005824e14db3395cece49daa312e1f379
CMake Version: 3.28.3
System: Linux-6.14.0-27-generic
Arch: aarch64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt
```

**Comment by kKPulla** [comment]
@zhztheplayer I still see the build failure in the CI signals - https://github.com/facebookincubator/velox/actions/runs/16673912573/job/47196107207?pr=14310

Is this ready to be merged?

**Comment by zhztheplayer** [comment]
Hi @kKPulla , it looks like the fuzzer jobs always run on the main branch code so we can ignore that CI failure :)

**Comment by MBkkt** [comment]
https://github.com/facebookincubator/velox/pull/14310#issuecomment-3145062882

@zhztheplayer yeah, but my statement about C++20 was about different build error (trivial dtor requirement)
