### PR TITLE
fix: Remove VLA usage in ToJson functions for macOS compatibility

### LINKED ISSUE #14479: Velox build seems to be failing on MacOS after recent change
### Problem description

Velox build with Gluten seems to be failing with error:
ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:47:15: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
   47 |   char buffer[maxSize];

It seems ot be failing after https://github.com/facebookincubator/velox/commit/a871a7541c4669e64407c2a619ba53cda4821a64 change is landed 

### System information

Velox System Info v0.0.2
Commit: b41f9fb591f9e814acd2b5ef3a98081693ebd5a5
CMake Version: 3.31.8
System: Darwin-24.6.0
Arch: arm64
C++ Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
C++ Compiler Version: 17.0.0.17000013
C Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
C Compiler Version: 17.0.0.17000013
CMake Prefix Path: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/Applications/CMake.app/Contents;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

### CMake log

```bash
incubator-gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:47:15: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
   47 |   char buffer[maxSize];
      |               ^~~~~~~
incubator-gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:47:15: note: initializer of 'maxSize' is not a constant expression
incubator-gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:46:16: note: declared here
   46 |   const size_t maxSize = DecimalUtil::maxStringViewSize(precision, scale);
      |                ^
incubator-gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:217:17: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
  217 |     char buffer[maxSize];
      |                 ^~~~~~~
incubator-gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:217:17: note: initializer of 'maxSize' is not a constant expression
incubator-gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:216:16: note: declared here
  216 |     const auto maxSize = formatter->maxResultSize(options.timeZone);
      |                ^
incubator-gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:47:15: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
   47 |   char buffer[maxSize];
      |               ^~~~~~~
incubator-gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:146:5: note: in instantiation of function template specialization 'facebook::velox::functions::sparksql::detail::appendDecimal<long long>' requested here
  146 |     appendDecimal(value, *input.type(), result);
      |     ^
incubator-gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:47:15: note: initializer of 'maxSize' is not a constant expression
   47 |   char buffer[maxSize];
      |               ^
incubator-gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:46:16: note: declared here
   46 |   const size_t maxSize = DecimalUtil::maxStringViewSize(precision, scale);
      |                ^
incubator-gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:47:15: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
   47 |   char buffer[maxSize];
      |               ^~~~~~~
incubator-gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:160:3: note: in instantiation of function template specialization 'facebook::velox::functions::sparksql::detail::appendDecimal<__int128>' requested here
  160 |   appendDecimal(value, *input.type(), result);
      |   ^
incubator-gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:47:15: note: initializer of 'maxSize' is not a constant expression
   47 |   char buffer[maxSize];
      |               ^
incubator-gluten/ep/build-velox/build/velox_ep/./velox/functions/sparksql/ToJson.h:46:16: note: declared here
   46 |   const size_t maxSize = DecimalUtil::maxStringViewSize(precision, scale);
      |                ^
4 errors generated.
[412/527] Building CXX object v...gregates/MinMaxByAggregate.cpp.o
ninja: build stopped: subcommand failed.
make[1]: *** [build] Error 1
make: *** [release] Error 2
```

### PR DESCRIPTION
**Pull request by nimesh1601**
Remove VLA usage in ToJson functions for macOS compatibility
fixes #14479

### CODE REVIEW

File: velox/functions/sparksql/ToJson.h [hunk 1]
```diff
@@ -44,9 +44,11 @@ template <typename T>
 void appendDecimal(T value, const Type& type, std::string& result) {
   auto [precision, scale] = getDecimalPrecisionScale(type);
   const size_t maxSize = DecimalUtil::maxStringViewSize(precision, scale);
-  char buffer[maxSize];
-  size_t len = DecimalUtil::castToString(value, scale, maxSize, buffer);
-  result.append(buffer, len);
+  size_t oldSize = result.size();
```
Comment (PingLiuPing) [inline velox/functions/sparksql/ToJson.h:47]: I think the approach you mentioned in your issue is more cleaner and easy.
` std::vector<char> buffer(maxSize);`

**Comment by zml1206** [comment]
Duplicate of #14434

**Comment by nimesh1601** [comment]
Thanks @zml1206. Closing this
