### ISSUE TITLE
Folly BUNDLED mode doesnt work on MacOs 14.2 SDK

### ISSUE THREAD

**Issue by kgpai** [facebookincubator/velox#8446]
### Problem description

The current version of folly doesnt work with MacOs 14.2 SDK , due to the followign deprecated changes (Note that these have been removed from newer folly versions which we are trying to upgrade to). 

```
 /Users/kpai/src/velox/_build/debug/_deps/folly-src/folly/Range.h:197:12: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
 ``` 

### System information

MacOs 14.2 SDK

### CMake log

```bash
N/A
```

**Comment by czentgr** [comment]
I believe this is fixed by https://github.com/facebookincubator/velox/pull/7700 when folly is upgraded.
I did a test on MacOS and it compiled successfully.

**Comment by majetideepak** [comment]
@czentgr thanks for the update!
